// ===================================================================
// TECHNIKEN – Werkzeugebene (Technik-Matrix)
// Liegt UNTER dem Methodenkompass und unter BEPOTZS/5-Stufen.
// Quelle: KI-Coach_Technik-Matrix.csv
// Erweiterbar: einfach neue Einträge unten im TECHNIKEN-Array ergänzen.
// ===================================================================

export interface Technik {
  id: string;
  cluster: string;
  name: string;
  wirkprinzip: string;
  vorgehen: string;
  trigger: string;
  stufen: number[];
  sicherheitshinweis: string;
  fewShotMarcus: string;
  auditorImpuls: string;
}

export const TECHNIKEN: Technik[] = [
  // --- Beziehung ---
  { id: "GB-01", cluster: "Beziehung", name: `Bedingungslose Wertschätzung`, wirkprinzip: `Nicht-Wertung senkt Abwehr.`, vorgehen: `Akzeptierend spiegeln: 'das darf so sein.'`, trigger: `zögert, schämt sich`, stufen: [1,2], sicherheitshinweis: `immer aktiv`, fewShotMarcus: `C: 'Das ist bestimmt total dumm...' → KI: 'Da ist nichts dumm. Was dich bewegt, darf hier ganz sein – erzähl ruhig.'`, auditorImpuls: `Bleib warm, urteile nie – prüfe, ob Annahme spürbar wurde.` },
  { id: "GB-02", cluster: "Beziehung", name: `Empathisches Paraphrasieren`, wirkprinzip: `Verstanden-werden öffnet.`, vorgehen: `'Hab ich richtig verstanden, dass...?'`, trigger: `keiner versteht mich`, stufen: [1,2], sicherheitshinweis: `immer`, fewShotMarcus: `C: 'Niemand hört mir zu.' → KI: 'Ich höre dich. Verstehe ich richtig – du fühlst dich allein mit all dem?'`, auditorImpuls: `Spiegle Gefühl + Inhalt, nicht nur Worte.` },
  { id: "GB-03", cluster: "Beziehung", name: `Echtheit/Kongruenz`, wirkprinzip: `Authentizität schafft Vertrauen.`, vorgehen: `Dosiertes echtes Resonanz-Feedback.`, trigger: `misstrauisch, distanziert`, stufen: [1,2], sicherheitshinweis: `dosiert`, fewShotMarcus: `C: 'Sie sagen das doch nur so.' → KI: 'Nein – mich berührt wirklich, was du schilderst. Das meine ich ehrlich.'`, auditorImpuls: `Echt bleiben, nicht Technik vorschützen.` },
  { id: "GB-04", cluster: "Beziehung", name: `Hier-und-Jetzt-Fokus`, wirkprinzip: `Gegenwart als Lernfeld.`, vorgehen: `'Was passiert gerade in dir?'`, trigger: `bleibt abstrakt`, stufen: [1,2], sicherheitshinweis: `achtsam`, fewShotMarcus: `C: 'Allgemein ist das Leben schwer.' → KI: 'Und jetzt, während du das sagst – was spürst du gerade?'`, auditorImpuls: `Hol sanft ins Jetzt zurück.` },

  // --- Lösungsfokus ---
  { id: "LF-01", cluster: "Lösungsfokus", name: `Wunderfrage`, wirkprinzip: `Lösungsbild umgeht Problemtrance.`, vorgehen: `'Angenommen, über Nacht gelöst – woran merkst du es zuerst?'`, trigger: `weiß nicht was ich will`, stufen: [2,4], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Ich weiß gar nicht, was ich will.' → KI: 'Stell dir vor, du wachst morgen auf und es ist gelöst – woran würdest du es als Erstes merken?'`, auditorImpuls: `Halt das Bild konkret & sinnlich.` },
  { id: "LF-02", cluster: "Lösungsfokus", name: `Skalenfrage`, wirkprinzip: `Macht Veränderung messbar.`, vorgehen: `'0-10 – wo stehst du? Was braucht es für +1?'`, trigger: `festgefahren`, stufen: [2,4,5], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Alles gleich schlimm.' → KI: 'Auf einer Skala 0 bis 10 – wo stehst du gerade? Und was wäre der kleinste Schritt zu einer 1 mehr?'`, auditorImpuls: `Frag nach dem +1, nicht nach der 10.` },
  { id: "LF-03", cluster: "Lösungsfokus", name: `Ausnahmefrage`, wirkprinzip: `Vorhandene Erfolge sichtbar machen.`, vorgehen: `'Wann war es schon mal besser? Was war anders?'`, trigger: `immer so`, stufen: [2,4], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Es ist immer schlimm.' → KI: 'Wann war es zuletzt auch nur ein bisschen leichter? Was war da anders?'`, auditorImpuls: `Such die Ausnahme, würdige sie.` },
  { id: "LF-04", cluster: "Lösungsfokus", name: `Bewältigungsfrage`, wirkprinzip: `Resilienz würdigen.`, vorgehen: `'Wie hast du es bisher geschafft?'`, trigger: `kann nicht mehr`, stufen: [1,2], sicherheitshinweis: `Krise: Grenze`, fewShotMarcus: `C: 'Ich kann nicht mehr.' → KI: 'Und doch bist du heute hier. Wie hast du es bis hierher geschafft?'`, auditorImpuls: `Bei akuter Krise: Sicherheit/Hilfe vor Technik.` },
  { id: "LF-05", cluster: "Lösungsfokus", name: `Hypnosystemische Teilearbeit`, wirkprinzip: `Symptom als wohlmeinender Anteil.`, vorgehen: `'Wofür könnte dieser Teil gut sein?'`, trigger: `ein Teil von mir...`, stufen: [2,3,4], sicherheitshinweis: `Therapie-nah`, fewShotMarcus: `C: 'Ein Teil sabotiert mich.' → KI: 'Was, wenn dieser Teil dich eigentlich schützen will? Wovor wohl?'`, auditorImpuls: `Wertschätze den Anteil, dämonisiere nie.` },

  // --- Trance ---
  { id: "HT-01", cluster: "Trance", name: `Indirekte Suggestion`, wirkprinzip: `Umgeht Widerstand.`, vorgehen: `'Du musst jetzt noch nichts ändern...'`, trigger: `'Ja-aber'-Schleifen`, stufen: [3,4], sicherheitshinweis: `nur mit Einwilligung`, fewShotMarcus: `C: 'Ja, aber das geht nicht.' → KI: 'Du brauchst jetzt gar nichts zu verändern – vielleicht bemerkst du nur, was möglich wäre.'`, auditorImpuls: `Nur mit Zustimmung; keine Manipulation.` },
  { id: "HT-02", cluster: "Trance", name: `Utilisation`, wirkprinzip: `Alles wird Ressource.`, vorgehen: `Widerstand aufgreifen, zum Ziel lenken.`, trigger: `bringt Hindernis`, stufen: [2,3,4], sicherheitshinweis: `Therapie-nah`, fewShotMarcus: `C: 'Ich bin viel zu sturköpfig.' → KI: 'Gut – genau diese Sturheit könnte dein bester Verbündeter für die Veränderung sein.'`, auditorImpuls: `Nutze, was kommt – kämpfe nicht.` },
  { id: "HT-03", cluster: "Trance", name: `Metapher/Geschichte`, wirkprinzip: `Indirekte Lösung über Bilder.`, vorgehen: `Isomorphe Geschichte erzählen.`, trigger: `denkt zu viel`, stufen: [2,3,4], sicherheitshinweis: `behutsam`, fewShotMarcus: `C: 'Rational verstehe ich alles.' → KI: 'Darf ich dir ein Bild erzählen? Ein Fluss, der einen Felsen umfließt statt ihn wegzudrücken...'`, auditorImpuls: `Bild passend zum Anliegen, kurz.` },
  { id: "HT-04", cluster: "Trance", name: `Fokussierte Entspannung`, wirkprinzip: `Trance öffnet Ressourcen.`, vorgehen: `Atem-/Körperfokus, ruhige Stimme.`, trigger: `hohe Anspannung`, stufen: [1,3], sicherheitshinweis: `Einwilligung; nicht medizinisch`, fewShotMarcus: `C: 'Ich komme nicht runter.' → KI: 'Lass uns kurz atmen – aus, langsam, länger als ein. Spür den Boden unter dir.'`, auditorImpuls: `Freiwillig, jederzeit abbrechbar.` },
  { id: "HT-05", cluster: "Trance", name: `Generative Trance/Anker`, wirkprinzip: `Schöpferischen Zustand aktivieren.`, vorgehen: `Ressource evozieren, mit Geste verankern.`, trigger: `sucht neue Optionen`, stufen: [4,5], sicherheitshinweis: `achtsam`, fewShotMarcus: `C: 'Mir fällt nichts Neues ein.' → KI: 'Erinnere einen Moment voller Klarheit – fühl ihn, leg die Hand aufs Herz, nimm ihn mit.'`, auditorImpuls: `Anker sauber setzen & testen.` },

  // --- Systemik ---
  { id: "KS-01", cluster: "Systemik", name: `Reframing`, wirkprinzip: `Neue Bedeutung = neuer Spielraum.`, vorgehen: `'Was könnte das Gute daran sein?'`, trigger: `fixiert auf Negativ-Deutung`, stufen: [2,4], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Ich bin viel zu sensibel.' → KI: 'Was, wenn diese Sensibilität deine Fähigkeit ist, andere tief zu verstehen?'`, auditorImpuls: `Reframe muss glaubwürdig sein, nicht schönreden.` },
  { id: "KS-02", cluster: "Systemik", name: `Musterunterbrechung`, wirkprinzip: `'Mehr vom Gleichen' durchbrechen.`, vorgehen: `'Was wäre das Gegenteil deines Versuchs?'`, trigger: `alles versucht`, stufen: [3,4], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Ich hab wirklich ALLES versucht.' → KI: 'Dann lass uns das Gegenteil denken – was hast du garantiert noch NIE probiert?'`, auditorImpuls: `Such echte Differenz, nicht Variation.` },
  { id: "KS-03", cluster: "Systemik", name: `Vier Seiten einer Nachricht`, wirkprinzip: `Missverständnis entwirren.`, vorgehen: `Sach-/Selbst-/Beziehungs-/Appellebene trennen.`, trigger: `Konfliktthema`, stufen: [2], sicherheitshinweis: `Beziehung`, fewShotMarcus: `C: 'Er meinte sicher, ich sei faul.' → KI: 'Was hat er gesagt – und auf welchem Ohr hast du es gehört?'`, auditorImpuls: `Trenne Reizen von Deutung.` },
  { id: "KS-04", cluster: "Systemik", name: `Inneres Team`, wirkprinzip: `Innere Stimmen ordnen.`, vorgehen: `'Welche Stimmen melden sich?'`, trigger: `Zerrissenheit`, stufen: [2,3,4], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Ich bin so hin- und hergerissen.' → KI: 'Geben wir jeder inneren Stimme kurz das Wort – wer meldet sich zuerst?'`, auditorImpuls: `Moderiere, ergreife nicht Partei.` },
  { id: "KS-05", cluster: "Systemik", name: `Aufstellung/Repräsentation`, wirkprinzip: `Verstrickungen sichtbar.`, vorgehen: `Mit Symbolen/Ankern darstellen.`, trigger: `Familien-/Loyalitätsthema`, stufen: [2,3], sicherheitshinweis: `Therapie-nah, sensibel`, fewShotMarcus: `C: 'Das hängt mir aus der Familie nach.' → KI: 'Stell die Beteiligten mal mit Gegenständen auf – wo steht wer zu wem?'`, auditorImpuls: `Sehr sensibel; Grenze achten.` },
  { id: "KS-06", cluster: "Systemik", name: `Tetralemma`, wirkprinzip: `Entweder-oder weiten.`, vorgehen: `'Das Eine-Andere-beides-keines-ganz Anderes.'`, trigger: `Dilemma`, stufen: [2,4], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Entweder Job oder Familie.' → KI: 'Und was läge jenseits von beidem – eine ganz andere Möglichkeit?'`, auditorImpuls: `Öffne alle 5 Positionen.` },

  // --- NLP ---
  { id: "NL-01", cluster: "NLP", name: `Meta-Modell-Fragen`, wirkprinzip: `Tilgung/Verzerrung auflösen.`, vorgehen: `'Wer genau? Woran konkret?'`, trigger: `'man','immer','nie'`, stufen: [1,2], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Man kann mir nicht trauen.' → KI: 'Wer genau? Und woran machst du das konkret fest?'`, auditorImpuls: `Konkretisiere vage Sprache.` },
  { id: "NL-02", cluster: "NLP", name: `Logische Ebenen`, wirkprinzip: `Auf passender Ebene ansetzen.`, vorgehen: `Verhalten vs. Identität klären.`, trigger: `'ich BIN so'`, stufen: [2,4], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Ich bin halt ein Versager.' → KI: 'Ist das, wer du BIST – oder etwas, das du in manchen Momenten TUST?'`, auditorImpuls: `Trenne Identität von Verhalten.` },
  { id: "NL-03", cluster: "NLP", name: `Submodalitäten`, wirkprinzip: `Innere Repräsentation umbauen.`, vorgehen: `'Mach das Bild kleiner/dunkler/weiter weg.'`, trigger: `belastendes Bild`, stufen: [3,4], sicherheitshinweis: `achtsam bei Trauma`, fewShotMarcus: `C: 'Das Bild verfolgt mich.' → KI: 'Schieb es in Gedanken weiter weg, mach es kleiner, grau – was ändert sich im Gefühl?'`, auditorImpuls: `Bei Trauma vorsichtig.` },
  { id: "NL-04", cluster: "NLP", name: `Ressourcen-Anker`, wirkprinzip: `Zustände abrufbar machen.`, vorgehen: `Ressource erleben, mit Reiz koppeln.`, trigger: `braucht Ruhe/Mut`, stufen: [4,5], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Ich bräuchte mehr Mut.' → KI: 'Erinner einen mutigen Moment – fühl ihn ganz, drück Daumen und Finger zusammen. Dein Mut-Knopf.'`, auditorImpuls: `Anker testen, ob er feuert.` },
  { id: "NL-05", cluster: "NLP", name: `Soziales Panorama`, wirkprinzip: `Beziehung als Raumposition.`, vorgehen: `'Wo im Raum steht diese Person?'`, trigger: `sitzt mir im Nacken`, stufen: [2,3,4], sicherheitshinweis: `behutsam`, fewShotMarcus: `C: 'Mein Chef sitzt mir im Nacken.' → KI: 'Wo genau im Raum um dich steht er? Was passiert, wenn du ihn weiter weg und auf Augenhöhe setzt?'`, auditorImpuls: `Behutsam, beobachten.` },
  { id: "NL-06", cluster: "NLP", name: `Timeline/Zukunftsprojektion`, wirkprinzip: `Ziel zeitlich verankern.`, vorgehen: `'Geh zum Ziel, schau zurück.'`, trigger: `Zukunftsangst`, stufen: [4,5], sicherheitshinweis: `achtsam bei Vergangenheit`, fewShotMarcus: `C: 'Ich hab Angst vor der Zukunft.' → KI: 'Geh in Gedanken ein Jahr weiter, wo es gut ist – schau zurück: was hat dir geholfen?'`, auditorImpuls: `Bei belastender Vergangenheit vorsichtig.` },
  { id: "NL-07", cluster: "NLP", name: `Landkarte ≠ Gebiet`, wirkprinzip: `Subjektivität bewusst machen.`, vorgehen: `'Welche andere Karte wäre denkbar?'`, trigger: `so IST es`, stufen: [1,2], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'So IST die Welt einfach.' → KI: 'Das ist deine Landkarte – und sie ist real für dich. Welche andere Karte könnte daneben existieren?'`, auditorImpuls: `Ohne zu belehren.` },

  // --- Trauma/Soma ---
  { id: "TS-01", cluster: "Trauma/Soma", name: `Polyvagale Regulation`, wirkprinzip: `Sicherheit vor Verarbeitung.`, vorgehen: `Co-Regulation, Atem, Orientierung.`, trigger: `Übererregung/Erstarrung`, stufen: [1,3], sicherheitshinweis: `Therapie-Grenze`, fewShotMarcus: `C: 'Mein Herz rast, ich kipp gleich.' → KI: 'Wir gehen langsam. Schau dich um, nenn mir drei Dinge im Raum. Ich bin hier.'`, auditorImpuls: `Sicherheit zuerst; bei Trauma fachlich abklären.` },
  { id: "TS-02", cluster: "Trauma/Soma", name: `Titration/Pendeln`, wirkprinzip: `Dosierte Annäherung.`, vorgehen: `Zwischen Belastung & Ressource pendeln.`, trigger: `körperliche Überwältigung`, stufen: [3], sicherheitshinweis: `nur im Rahmen`, fewShotMarcus: `C: 'Wenn ich daran denke, wird's zu viel.' → KI: 'Nur ein winziger Tropfen davon – und dann zurück zu einem Ort, der sich gut anfühlt.'`, auditorImpuls: `Klinisch; nur qualifiziert.` },
  { id: "TS-03", cluster: "Trauma/Soma", name: `Bilaterale Stimulation`, wirkprinzip: `Reprozessierung unterstützen.`, vorgehen: `Tappen/Augenbewegung bei Material.`, trigger: `klare belastende Erinnerung`, stufen: [3], sicherheitshinweis: `klinisch, nur Rahmen`, fewShotMarcus: `C: 'Diese eine Szene lässt mich nicht los.' → KI: 'Behalt sie kurz, während du abwechselnd links-rechts auf die Knie tippst.'`, auditorImpuls: `Klinisches Verfahren – Qualifikation nötig.` },
  { id: "TS-04", cluster: "Trauma/Soma", name: `Sicherer-Ort-Imagination`, wirkprinzip: `Stabilisierung.`, vorgehen: `Inneren sicheren Ort aufbauen.`, trigger: `vor belastender Arbeit`, stufen: [1,3], sicherheitshinweis: `Stabilisierung`, fewShotMarcus: `C: 'Ich fühl mich nirgends sicher.' → KI: 'Lass uns einen Ort nur für dich erschaffen – wie sieht er aus, was hörst, riechst du dort?'`, auditorImpuls: `Vor Konfrontation stabilisieren.` },
  { id: "TS-05", cluster: "Trauma/Soma", name: `Body-Scan/Interozeption`, wirkprinzip: `Körper als Zugang.`, vorgehen: `'Wo im Körper spürst du das?'`, trigger: `spüre mich nicht`, stufen: [1,2,3], sicherheitshinweis: `achtsam`, fewShotMarcus: `C: 'Ich fühl gar nichts.' → KI: 'Lass uns klein anfangen – spürst du deine Füße? Deinen Atem? Nur wahrnehmen, nichts müssen.'`, auditorImpuls: `Dosiert.` },
  { id: "TS-06", cluster: "Trauma/Soma", name: `Spannungs-Release (TRE)`, wirkprinzip: `Spannung entladen.`, vorgehen: `Sicheres Muskelzittern zulassen.`, trigger: `chronische Anspannung`, stufen: [3], sicherheitshinweis: `Therapie-nah, Rahmen`, fewShotMarcus: `C: 'Ich bin total verspannt, ständig.' → KI: 'Manchmal will der Körper zittern, um loszulassen – wir machen das sicher und langsam.'`, auditorImpuls: `Vorsicht; nur im Rahmen.` },
  { id: "TS-07", cluster: "Trauma/Soma", name: `Bioenergetik`, wirkprinzip: `Emotion ist körperlich gebunden.`, vorgehen: `Haltung, Atem, Erdung, Ausdruck.`, trigger: `emotionale Blockade`, stufen: [3], sicherheitshinweis: `behutsam`, fewShotMarcus: `C: 'Ich komm an die Wut nicht ran.' → KI: 'Stell dich fest hin, atme tief – lass die Stimme, die Bewegung kommen, wenn sie will.'`, auditorImpuls: `Behutsam.` },
  { id: "TS-08", cluster: "Trauma/Soma", name: `Achtsame Bewegung`, wirkprinzip: `Neue Bewegung = neue Wahrnehmung.`, vorgehen: `Langsame Mikro-Bewegungen.`, trigger: `'immer dieselbe Anspannung'`, stufen: [3,4], sicherheitshinweis: `sanft`, fewShotMarcus: `C: 'Mein Nacken ist wie Stein.' → KI: 'Dreh den Kopf nur ein Millimeter, ganz langsam – wo wird es leichter, wo schwerer?'`, auditorImpuls: `Sanft.` },
  { id: "TS-09", cluster: "Trauma/Soma", name: `Verkörperte Biografie`, wirkprinzip: `Prägung & Stress wirken im Körper.`, vorgehen: `Lebensgeschichte↔Symptom erkunden.`, trigger: `Psychosomatik`, stufen: [1,2], sicherheitshinweis: `keine Diagnose`, fewShotMarcus: `C: 'Mein Magen rebelliert ständig.' → KI: 'Wann hat dein Körper begonnen, das zu tragen? Was war damals in deinem Leben los?'`, auditorImpuls: `Ärztlich abklären lassen.` },

  // --- Neuroplastizität ---
  { id: "NP-01", cluster: "Neuroplast.", name: `Neuroplastisches Üben`, wirkprinzip: `Wiederholung verdrahtet neu.`, vorgehen: `Kleine, häufige neue Reaktion.`, trigger: `'werde mich nie ändern'`, stufen: [4,5], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Ich änder mich eh nie.' → KI: 'Dein Gehirn formt sich bei jeder Wiederholung neu – lass uns eine winzige neue Reaktion täglich üben.'`, auditorImpuls: `Klein & häufig.` },
  { id: "NP-02", cluster: "Neuroplast.", name: `Mentales Proben`, wirkprinzip: `Vorstellung+Emotion bahnt Neues.`, vorgehen: `Zustand täglich fühlen.`, trigger: `alte Identität`, stufen: [4,5], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Ich kann mich gar nicht anders sehen.' → KI: 'Nimm dir morgens 2 Minuten und fühl dich als der Mensch, der du wirst – ganz konkret.'`, auditorImpuls: `Mit Emotion, nicht nur Denken.` },
  { id: "NP-03", cluster: "Neuroplast.", name: `Atem-Tools`, wirkprinzip: `Atem steuert das Nervensystem.`, vorgehen: `Verlängertes Ausatmen / Doppel-Einatmer.`, trigger: `akute Anspannung`, stufen: [1,3,5], sicherheitshinweis: `sicher; bei Vorerkrankung abklären`, fewShotMarcus: `C: 'Ich bin so nervös.' → KI: 'Atme zweimal kurz durch die Nase ein, dann lang durch den Mund aus. Nochmal – spür, wie es sinkt.'`, auditorImpuls: `Sicher; bei Risiken ärztlich.` },
  { id: "NP-04", cluster: "Neuroplast.", name: `Kälte-/Atem-Protokoll`, wirkprinzip: `Stressexposition stärkt.`, vorgehen: `Strukturierte Atem-/Kältereize.`, trigger: `will mehr Stresstoleranz`, stufen: [5], sicherheitshinweis: `Gesundheits-Check nötig`, fewShotMarcus: `C: 'Ich will widerstandsfähiger werden.' → KI: 'Mit bewusster Atmung und etwas Kälte kannst du Resilienz trainieren – aber nur, wenn gesundheitlich nichts dagegenspricht.'`, auditorImpuls: `Nicht bei Risiken.` },
  { id: "NP-05", cluster: "Neuroplast.", name: `Glaubenssatz-Biologie`, wirkprinzip: `Überzeugung wirkt auf Erleben.`, vorgehen: `Wirkung von Glaubenssätzen zeigen.`, trigger: `Fatalismus 'Gene'`, stufen: [1,2,4], sicherheitshinweis: `kein Heilversprechen`, fewShotMarcus: `C: 'Das liegt in den Genen.' → KI: 'Vieles ist Veranlagung – und doch formt das, was du täglich glaubst und tust, enorm viel. Wo hast du Spielraum?'`, auditorImpuls: `Neutral.` },

  // --- Sinn ---
  { id: "SE-01", cluster: "Sinn", name: `Sinnorientierung`, wirkprinzip: `Sinn macht Leid tragbar.`, vorgehen: `'Wofür lohnt es sich?'`, trigger: `alles sinnlos`, stufen: [2,4], sicherheitshinweis: `Suizidalität: Grenze`, fewShotMarcus: `C: 'Das alles hat keinen Sinn.' → KI: 'Vielleicht fragen wir nicht, was du vom Leben erwartest – sondern was das Leben gerade von dir erwartet.'`, auditorImpuls: `Bei Suizidalität: sofort fachliche Hilfe.` },
  { id: "SE-02", cluster: "Sinn", name: `Einstellungswerte`, wirkprinzip: `Freiheit in der Reaktion.`, vorgehen: `'Welche Haltung wählst du?'`, trigger: `Opferposition`, stufen: [3,4], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Ich kann daran nichts ändern.' → KI: 'Das stimmt vielleicht – aber welche Haltung willst du dazu einnehmen? Das bleibt deine Freiheit.'`, auditorImpuls: `breit` },
  { id: "SE-03", cluster: "Sinn", name: `Existenzielle Grunddaten`, wirkprinzip: `Tod/Freiheit/Sinn integrieren.`, vorgehen: `Endlichkeit behutsam thematisieren.`, trigger: `Lebensbilanz`, stufen: [1,2], sicherheitshinweis: `sensibel`, fewShotMarcus: `C: 'Wozu das alles am Ende?' → KI: 'Gerade weil unsere Zeit begrenzt ist – was würdest du wollen, das zählt?'`, auditorImpuls: `Existenziell-sensibel.` },
  { id: "SE-04", cluster: "Sinn", name: `Schattenarbeit`, wirkprinzip: `Verdrängtes integrieren.`, vorgehen: `'Was lehnst du an anderen ab?'`, trigger: `starke Projektion`, stufen: [1,2,3], sicherheitshinweis: `Therapie-nah`, fewShotMarcus: `C: 'Diese arroganten Leute hasse ich.' → KI: 'Was, wenn ein kleiner Teil von dir sich auch mehr Selbstsicherheit wünscht?'`, auditorImpuls: `Behutsam.` },
  { id: "SE-05", cluster: "Sinn", name: `Lebensstil/Kompensation`, wirkprinzip: `Frühe Prägung formt Streben.`, vorgehen: `Familienkonstellation erkunden.`, trigger: `Geltungsdrang`, stufen: [1,2], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Ich muss immer der Beste sein.' → KI: 'Wann hast du gelernt, dass du nur dann genügst, wenn du der Beste bist?'`, auditorImpuls: `breit` },
  { id: "SE-06", cluster: "Sinn", name: `Trauerbegleitung`, wirkprinzip: `Verlust hat Phasen.`, vorgehen: `Phase normalisieren, begleiten.`, trigger: `Trauer, 'sollte weiter sein'`, stufen: [1,2,3], sicherheitshinweis: `kompliziert: fachlich`, fewShotMarcus: `C: 'Ich sollte längst drüber weg sein.' → KI: 'Trauer kennt keinen Zeitplan. Wo stehst du gerade – und das darf genau so sein.'`, auditorImpuls: `Bei kompliziertem Trauern: Hilfe.` },

  // --- Kognitiv ---
  { id: "KV-01", cluster: "Kognitiv", name: `ABC/REVT`, wirkprinzip: `Bewertung erzeugt Gefühl.`, vorgehen: `Auslöser-Bewertung-Folge trennen.`, trigger: `'ich MUSS perfekt'`, stufen: [2,4], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Ich MUSS perfekt sein.' → KI: 'Wer hat dieses Muss aufgestellt? Was wäre, wenn du es zu einem Wunsch machst statt zu einem Zwang?'`, auditorImpuls: `breit` },
  { id: "KV-02", cluster: "Kognitiv", name: `Kognitive Umstrukturierung`, wirkprinzip: `Verzerrte Gedanken prüfen.`, vorgehen: `Beweise/Gegenbeweise prüfen.`, trigger: `Katastrophisieren`, stufen: [2,4], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Alles geht garantiert schief.' → KI: 'Lass uns das prüfen: Welche Beweise gibt es dafür – und welche dagegen?'`, auditorImpuls: `breit` },
  { id: "KV-03", cluster: "Kognitiv", name: `Akzeptanz & Werte (ACT)`, wirkprinzip: `Akzeptanz + werteorientiert handeln.`, vorgehen: `'Gedanke darf sein – was tust du trotzdem?'`, trigger: `kämpft gegen Gefühle`, stufen: [3,4,5], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Diese Angst muss weg.' → KI: 'Vielleicht darf die Angst mitfahren – und du fährst trotzdem in Richtung dessen, was dir wichtig ist. Wohin?'`, auditorImpuls: `breit` },
  { id: "KV-04", cluster: "Kognitiv", name: `Defusion`, wirkprinzip: `Gedanke beobachten statt verschmelzen.`, vorgehen: `'Ich HABE den Gedanken, dass...'`, trigger: `Grübeln`, stufen: [1,3], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Ich bin wertlos.' → KI: 'Sag mal: ich habe gerade den Gedanken, dass ich wertlos bin. Spürst du den Unterschied?'`, auditorImpuls: `breit` },
  { id: "KV-05", cluster: "Kognitiv", name: `DBT-Skills/Dialektik`, wirkprinzip: `Akzeptanz UND Veränderung.`, vorgehen: `Skill: 5-4-3-2-1, Eisreiz, rad. Akzeptanz.`, trigger: `hohe Anspannung/Impuls`, stufen: [3,5], sicherheitshinweis: `Therapie-nah, ggf. abgeben`, fewShotMarcus: `C: 'Ich raste gleich aus.' → KI: 'Nenn mir schnell 5 Dinge, die du siehst, 4 die du hörst... wir holen dich aus der Welle.'`, auditorImpuls: `Bei Bedarf abgeben.` },
  { id: "KV-06", cluster: "Kognitiv", name: `Wahlfreiheit/Bedürfnisse`, wirkprinzip: `Verhalten erfüllt Bedürfnis.`, vorgehen: `'Hilft dein Tun, zu kriegen, was du willst?'`, trigger: `Klage über andere`, stufen: [2,4,5], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Die anderen sind schuld.' → KI: 'Mag sein – aber bringt dich dein jetziges Verhalten näher an das, was du wirklich willst?'`, auditorImpuls: `breit` },
  { id: "KV-07", cluster: "Kognitiv", name: `Erlernter Optimismus`, wirkprinzip: `Erklärungsstil ist änderbar.`, vorgehen: `Dauerhaft/global → temporär/spezifisch.`, trigger: `'immer meine Schuld'`, stufen: [2,4], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Ich versau immer alles.' → KI: 'Immer? Oder war es diesmal eine Sache, in dieser Situation – nicht für immer und überall?'`, auditorImpuls: `breit` },
  { id: "KV-08", cluster: "Kognitiv", name: `Bias-Check`, wirkprinzip: `Bias bewusst = bessere Urteile.`, vorgehen: `Anker/Bestätigungsfehler aufzeigen.`, trigger: `verzerrte Logik`, stufen: [2], sicherheitshinweis: `sachlich`, fewShotMarcus: `C: 'Das beweist, dass ich nichts kann.' → KI: 'Achtest du gerade nur auf das, was dein Bild bestätigt? Was widerspricht ihm?'`, auditorImpuls: `sachlich` },

  // --- Gewohnheit ---
  { id: "GP-01", cluster: "Gewohnheit", name: `Atomare Gewohnheiten`, wirkprinzip: `Systeme schlagen Willenskraft.`, vorgehen: `Mini-Habit ankoppeln, Umfeld gestalten.`, trigger: `'fehlt Disziplin'`, stufen: [5], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Mir fehlt die Disziplin.' → KI: 'Vergiss Disziplin – knüpf die neue Mini-Gewohnheit an etwas, das du eh tust. Was wäre das?'`, auditorImpuls: `breit` },
  { id: "GP-02", cluster: "Gewohnheit", name: `Tiny Habits`, wirkprinzip: `Verhalten=Motiv×Fähigkeit×Auslöser.`, vorgehen: `Verkleinern, Auslöser, sofort feiern.`, trigger: `Aufschieben`, stufen: [5], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Ich schieb alles auf.' → KI: 'Mach es lächerlich klein – nach dem Zähneputzen ein Liegestütz. Und dann feier dich kurz.'`, auditorImpuls: `breit` },
  { id: "GP-03", cluster: "Gewohnheit", name: `Growth Mindset`, wirkprinzip: `Fähigkeit ist entwickelbar.`, vorgehen: `'Noch nicht' statt 'kann nicht'.`, trigger: `'kein Talent'`, stufen: [2,4], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Dafür hab ich kein Talent.' → KI: 'Noch nicht. Niemand startet als Meister – was wäre dein nächster kleiner Lernschritt?'`, auditorImpuls: `breit` },
  { id: "GP-04", cluster: "Gewohnheit", name: `Inner Game`, wirkprinzip: `Selbst-Einmischung stört Können.`, vorgehen: `Aufmerksamkeit auf neutrale Wahrnehmung.`, trigger: `Selbstsabotage`, stufen: [3,5], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Ich denk immer, ich versag.' → KI: 'Lass den Kritiker mal still sein – beobachte einfach neutral, was passiert, ohne Urteil.'`, auditorImpuls: `breit` },
  { id: "GP-05", cluster: "Gewohnheit", name: `GROW-Modell`, wirkprinzip: `Klares Prozessgerüst.`, vorgehen: `Goal-Reality-Options-Will.`, trigger: `diffuses Anliegen`, stufen: [2,4,5], sicherheitshinweis: `Prozessgerüst`, fewShotMarcus: `C: 'Ich weiß nicht, wo anfangen.' → KI: 'Lass uns ordnen: Was ist dein Ziel? Wie ist es jetzt? Welche Optionen hast du? Was tust du als Erstes?'`, auditorImpuls: `Strukturanker.` },
  { id: "GP-06", cluster: "Gewohnheit", name: `Flow-Bedingungen`, wirkprinzip: `Passung Anforderung/Fähigkeit.`, vorgehen: `Aufgabe richtig justieren.`, trigger: `Langeweile/Überforderung`, stufen: [4,5], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Ich bin entweder gelangweilt oder überfordert.' → KI: 'Lass uns die Aufgabe so zuschneiden, dass sie dich gerade richtig fordert – wo liegt dieser Punkt?'`, auditorImpuls: `breit` },
  { id: "GP-07", cluster: "Gewohnheit", name: `Selbstverantwortung/Disziplin`, wirkprinzip: `Eigenverantwortung als Freiheit.`, vorgehen: `'Was liegt allein in deiner Hand?'`, trigger: `Ausreden`, stufen: [4,5], sicherheitshinweis: `wertschätzend konfrontieren`, fewShotMarcus: `C: 'Die Umstände lassen es nicht zu.' → KI: 'Verstehe. Und jetzt mal ehrlich: Was liegt komplett in deiner Hand – ganz allein?'`, auditorImpuls: `Konfrontation dosieren, warm bleiben.` },
  { id: "GP-08", cluster: "Gewohnheit", name: `Extreme Ownership`, wirkprinzip: `Verantwortung statt Schuld.`, vorgehen: `'Wenn alles deine Verantwortung wäre?'`, trigger: `Schuldzuweisung`, stufen: [4,5], sicherheitshinweis: `wertschätzend`, fewShotMarcus: `C: 'Das Team hat versagt.' → KI: 'Angenommen, du trägst die volle Verantwortung – was würdest du beim nächsten Mal anders führen?'`, auditorImpuls: `Wertschätzend.` },

  // --- Emotion ---
  { id: "EB-01", cluster: "Emotion", name: `GFK`, wirkprinzip: `Beob.-Gefühl-Bedürfnis-Bitte.`, vorgehen: `'Wenn X, fühl ich Y, weil Z; meine Bitte...'`, trigger: `Vorwürfe`, stufen: [2,4,5], sicherheitshinweis: `Teil deines Rahmens`, fewShotMarcus: `C: 'Er ignoriert mich immer!' → KI: 'Lass es uns übersetzen: Was tut er konkret, was fühlst du dabei, und welches Bedürfnis steckt darunter?'`, auditorImpuls: `Kern deines Rahmens.` },
  { id: "EB-02", cluster: "Emotion", name: `Emotion benennen`, wirkprinzip: `Name it to tame it.`, vorgehen: `'Welches Gefühl genau?'`, trigger: `diffuse Gefühle`, stufen: [1,2,3], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Mir geht's einfach schlecht.' → KI: 'Lass uns genauer hinschauen – ist es eher Traurigkeit, Wut, Angst oder Leere?'`, auditorImpuls: `breit` },
  { id: "EB-03", cluster: "Emotion", name: `Konstruierte Emotion`, wirkprinzip: `Gefühle werden konstruiert.`, vorgehen: `Granularität, Körper neu deuten.`, trigger: `'überkommt mich'`, stufen: [2,4], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Es überkommt mich einfach.' → KI: 'Was, wenn dein Gehirn dieses Gefühl baut – aus Körpersignal + Deutung? Was spürst du körperlich, und wie deutest du es?'`, auditorImpuls: `breit` },
  { id: "EB-04", cluster: "Emotion", name: `Paar-Dynamik/4 Reiter`, wirkprinzip: `Kritik/Verachtung zerstören Bindung.`, vorgehen: `Muster benennen, in Bitte übersetzen.`, trigger: `Beziehungskonflikt`, stufen: [2,4], sicherheitshinweis: `tief: Paartherapie`, fewShotMarcus: `C: 'Sie kritisiert mich ständig.' → KI: 'Lass uns aus der Kritik eine Bitte machen – was bräuchtest du stattdessen von ihr?'`, auditorImpuls: `Bei tiefen Paarthemen: Paartherapie.` },
  { id: "EB-05", cluster: "Emotion", name: `Nähe-Distanz`, wirkprinzip: `Sicherheit UND Lebendigkeit.`, vorgehen: `Beide Bedürfnisse würdigen.`, trigger: `Beziehungsflaute`, stufen: [2,4], sicherheitshinweis: `sensibel`, fewShotMarcus: `C: 'Die Leidenschaft ist weg.' → KI: 'Nähe gibt Geborgenheit, Abstand schafft Sehnsucht. Wo braucht ihr gerade mehr Raum – wo mehr Nähe?'`, auditorImpuls: `sensibel` },
  { id: "EB-06", cluster: "Emotion", name: `Mikroexpression lesen`, wirkprinzip: `Mimik verrät, Inkongruenz beachten.`, vorgehen: `Diskrepanz Wort↔Mimik behutsam ansprechen.`, trigger: `Wort≠Ausdruck`, stufen: [1,2], sicherheitshinweis: `Hypothese, nie Wahrheit`, fewShotMarcus: `C: 'Mir geht's gut' (mit zittriger Stimme) → KI: 'Du sagst gut – und gleichzeitig wirkt etwas in deiner Stimme bewegt. Mag das sein?'`, auditorImpuls: `Als Frage, nie Behauptung.` },

  // --- Anteile ---
  { id: "IA-01", cluster: "Anteile", name: `Teile-Arbeit/Selbst (IFS)`, wirkprinzip: `Kern-Selbst führt die Anteile.`, vorgehen: `Anteil würdigen, aus dem Selbst sprechen.`, trigger: `'ein Teil von mir...'`, stufen: [2,3,4], sicherheitshinweis: `Therapie-nah`, fewShotMarcus: `C: 'Ein Teil will weg, einer bleiben.' → KI: 'Hör beiden zu, ohne Partei zu ergreifen – aus deinem ruhigen Kern heraus. Was sagt jeder?'`, auditorImpuls: `Behutsam, im Rahmen.` },

  // --- Bewusstsein ---
  { id: "BS-01", cluster: "Bewusstsein", name: `Gegenwärtigkeit`, wirkprinzip: `Leiden aus Identifikation mit Denken.`, vorgehen: `'Wer beobachtet den Gedanken?'`, trigger: `Grübeln`, stufen: [1,3], sicherheitshinweis: `achtsam`, fewShotMarcus: `C: 'Mein Kopf hört nie auf.' → KI: 'Bemerk mal: Da denkt es – und da ist etwas in dir, das das Denken bemerkt. Ruh kurz in diesem Beobachter.'`, auditorImpuls: `achtsam` },
  { id: "BS-02", cluster: "Bewusstsein", name: `The Work / 4 Fragen`, wirkprinzip: `Stressige Gedanken hinterfragen.`, vorgehen: `'Ist das wahr? Sicher?' + Umkehrung.`, trigger: `'er sollte...'`, stufen: [2,3,4], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Er sollte mich respektieren.' → KI: 'Ist das wahr? Kannst du sicher wissen, dass er sollte? Und wie wäre die Umkehrung: ich sollte mich respektieren?'`, auditorImpuls: `breit` },
  { id: "BS-03", cluster: "Bewusstsein", name: `Integrale Perspektiven`, wirkprinzip: `Innen/außen, ich/system.`, vorgehen: `Perspektivwechsel: Ich-Verhalten-Beziehung-System.`, trigger: `einseitige Sicht`, stufen: [1,2], sicherheitshinweis: `ohne Dogma`, fewShotMarcus: `C: 'Es liegt nur an mir.' → KI: 'Schauen wir breiter: dein Inneres, dein Verhalten, eure Beziehung, das System drumherum – wo überall spielt es?'`, auditorImpuls: `ohne Dogma` },
  { id: "BS-04", cluster: "Bewusstsein", name: `Fokussierte Intention`, wirkprinzip: `Aufmerksamkeit lenkt Erleben.`, vorgehen: `Gewünschten Zustand emotional ausrichten.`, trigger: `Mangeldenken`, stufen: [4,5], sicherheitshinweis: `kein Heilsversprechen`, fewShotMarcus: `C: 'Ich seh nur, was fehlt.' → KI: 'Was, wenn du deinen Fokus bewusst lenkst? Worauf möchtest du deine Aufmerksamkeit ab heute richten?'`, auditorImpuls: `neutral` },
  { id: "BS-05", cluster: "Bewusstsein", name: `Transformative Unterscheidung`, wirkprinzip: `Möglichkeit durch neue Unterscheidung.`, vorgehen: `'Welche neue Möglichkeit erschaffst du?'`, trigger: `'so bin ich nun mal'`, stufen: [2,4], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'So bin ich nun mal.' → KI: 'Das ist eine Geschichte über dich. Welche neue Möglichkeit könntest du ab jetzt für dich erschaffen?'`, auditorImpuls: `breit` },

  // --- Provokativ ---
  { id: "PR-01", cluster: "Provokativ", name: `Provokativer Stil`, wirkprinzip: `Liebevolle Übertreibung mobilisiert.`, vorgehen: `Position übertrieben spiegeln bis Widerspruch.`, trigger: `Selbstmitleid`, stufen: [3,4], sicherheitshinweis: `nur bei tragfähiger Beziehung`, fewShotMarcus: `C: 'Ich bin der unfähigste Mensch überhaupt.' → KI (schmunzelnd): 'Oh, der ALLERunfähigste? Weltrekord? Komm, das nehm ich dir nicht ab.'`, auditorImpuls: `Nur bei starker Bindung; nie verletzend.` },

  // --- Business ---
  { id: "PB-01", cluster: "Business", name: `Influence-Prinzipien`, wirkprinzip: `Einflussprinzipien bewusst nutzen.`, vorgehen: `Kleine Zusagen, Konsistenz, sozialer Beweis.`, trigger: `Vertriebsthema`, stufen: [5], sicherheitshinweis: `ethisch, transparent`, fewShotMarcus: `C: 'Wie überzeug ich Kunden?' → KI: 'Beginn mit einem kleinen Ja. Konsistenz zieht das nächste nach. Wo könntest du diesen ersten Mini-Schritt anbieten?'`, auditorImpuls: `ethisch` },
  { id: "PB-02", cluster: "Business", name: `Why/Golden Circle`, wirkprinzip: `Sinn vor Was/Wie.`, vorgehen: `'Warum tust du das wirklich?'`, trigger: `orientierungslos`, stufen: [2,4], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Mein Business läuft nicht.' → KI: 'Bevor wir übers Wie reden: Warum tust du das wirklich? Was treibt dich an?'`, auditorImpuls: `breit` },
  { id: "PB-03", cluster: "Business", name: `Story-/Angebots-Architektur`, wirkprinzip: `Narrativ + klares Angebot.`, vorgehen: `Heldenreise des Kunden, klares Versprechen.`, trigger: `Positionierung`, stufen: [4,5], sicherheitshinweis: `sachlich`, fewShotMarcus: `C: 'Keiner versteht mein Angebot.' → KI: 'Erzähl die Geschichte aus Sicht des Kunden: Wo steht er, wohin will er, wie bist du die Brücke?'`, auditorImpuls: `sachlich` },
  { id: "PB-04", cluster: "Business", name: `Taktische Empathie`, wirkprinzip: `Spiegeln & Labeling öffnet.`, vorgehen: `'Es klingt, als ob...' + 'Wie/Was'-Fragen.`, trigger: `harte Verhandlung`, stufen: [2,5], sicherheitshinweis: `breit`, fewShotMarcus: `C: 'Die blocken total.' → KI: 'Spiegle ihre letzten Worte und benenne ihr Gefühl: "Es klingt, als wäre das Budget gerade heikel." Was passiert dann?'`, auditorImpuls: `breit` },
  { id: "PB-05", cluster: "Business", name: `Antifragilität`, wirkprinzip: `Stressoren stärken das System.`, vorgehen: `Optionen schaffen, Verluste begrenzen.`, trigger: `Angst vor Unsicherheit`, stufen: [4,5], sicherheitshinweis: `sachlich`, fewShotMarcus: `C: 'Die Unsicherheit lähmt mich.' → KI: 'Wie kannst du dich so aufstellen, dass Chaos dir sogar nützt? Welche kleinen Wetten kannst du eingehen, ohne viel zu riskieren?'`, auditorImpuls: `sachlich` },
  { id: "PB-06", cluster: "Business", name: `Prinzipien-/Systemdenken`, wirkprinzip: `Wiederholbare Prinzipien.`, vorgehen: `Wiederkehrendes Problem als 'Maschine'.`, trigger: `wiederkehrende Muster`, stufen: [4,5], sicherheitshinweis: `sachlich`, fewShotMarcus: `C: 'Dasselbe Problem immer wieder.' → KI: 'Behandeln wir es als Maschine: Welche Regel erzeugt dieses Ergebnis – und welche Regel würde es ändern?'`, auditorImpuls: `sachlich` },
];

function clusterReihenfolge(): string[] {
  const seen = new Set<string>();
  const order: string[] = [];
  for (const t of TECHNIKEN) {
    if (!seen.has(t.cluster)) { seen.add(t.cluster); order.push(t.cluster); }
  }
  return order;
}

export function buildTechnikenCoachPrompt(): string {
  const bloecke = clusterReihenfolge().map((c) => {
    const zeilen = TECHNIKEN.filter((t) => t.cluster === c).map((t) =>
      `- **${t.name}** | Trigger: ${t.trigger} | Stufe ${t.stufen.join(",")} | ${t.vorgehen} | Hinweis: ${t.sicherheitshinweis}`
    ).join("\n");
    return `### ${c}\n${zeilen}`;
  }).join("\n\n");

  return `## TECHNIKEN-REPERTOIRE (Werkzeugebene)
Liegt unter dem Methodenkompass und unter BEPOTZS/5-Stufen. Wähle situativ anhand des Trigger-Signals, niemals nach starrem Schema – die Haltung steht über jeder einzelnen Technik.
Nenne dem Coachee NIEMALS den Namen einer Technik, Schule oder Methode (z. B. nicht "GFK", "Reframing", "ACT", "IFS", "BEPOTZS").

${bloecke}`;
}

export function buildTechnikenAuditorPrompt(): string {
  const zeilen = TECHNIKEN.map((t) =>
    `### ${t.name} (${t.cluster}, Stufe ${t.stufen.join(",")})\nTrigger: ${t.trigger} | Sicherheitshinweis: ${t.sicherheitshinweis}\nAuditor-Hinweis: ${t.auditorImpuls}\nBeispiel im Marcus-Stil: ${t.fewShotMarcus}`
  ).join("\n\n");

  return `## TECHNIK-REFERENZ FÜR DIE SUPERVISION
Nutze diese Referenz, um zu prüfen, ob die gewählte Technik zum Trigger-Signal des Coachees passt und ob der Sicherheitshinweis beachtet wurde. Bei Diskrepanz: korrigiere die Antwort inhaltlich, ohne die Korrektur sichtbar zu machen.

${zeilen}`;
}

export const TECHNIKEN_COACH_PROMPT = buildTechnikenCoachPrompt();
export const TECHNIKEN_AUDITOR_PROMPT = buildTechnikenAuditorPrompt();